apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: hyperenglish-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: node-api
        image: arthurrosa12112/node-web-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapi
  namespace: hyperenglish-api
spec:
  ports:
    - port: 80
  selector: 
    app: node-api
  type: LoadBalancer