resources:
- ingress.yaml
- deployment.yaml
- ingress-api.yaml
- issuer-api.yaml
- issuer.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registryldcp.azurecr.io/paymentexample
  newTag: 555.9.2
